"""be better?

Revision ID: 1996f5d83f58
Revises: 945c08fd1b71
Create Date: 2018-09-06 07:21:10.581963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1996f5d83f58'
down_revision = '945c08fd1b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('prehours', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('preminutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'preminutes')
    op.drop_column('activity', 'prehours')
    # ### end Alembic commands ###
