"""empty message

Revision ID: 58a99197b048
Revises: fa35f0db07cd
Create Date: 2018-11-27 18:58:08.044149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a99197b048'
down_revision = 'fa35f0db07cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'number')
    # ### end Alembic commands ###
