"""be better

Revision ID: 945c08fd1b71
Revises: a0fc2254f9f7
Create Date: 2018-09-06 07:09:02.000834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945c08fd1b71'
down_revision = 'a0fc2254f9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('task', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'task')
    # ### end Alembic commands ###
