"""love you again?

Revision ID: be7d5a6326b1
Revises: 8ec764abb710
Create Date: 2018-09-07 09:37:06.038255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7d5a6326b1'
down_revision = '8ec764abb710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('month_str', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'month_str')
    # ### end Alembic commands ###
