"""empty message

Revision ID: fa35f0db07cd
Revises: 7c2750fe1634
Create Date: 2018-11-14 14:12:59.422617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa35f0db07cd'
down_revision = '7c2750fe1634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('completion', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'completion')
    # ### end Alembic commands ###
